db:
  user: kemal
  password: kemal
  host: localhost
  port: 5432
  dbname: archive
access_key: ACCESS_KEY
secret_key: SECRET_KEY
region: sfo2
bucket: yt-annotation-archive
endpoint: digitaloceanspaces.com
content_threshold: 0.10
